import { Ticket } from './ticket-card.model';

export const dummyTickets: Ticket[] = [
  {
    "Customer Name": "John Doe",
    "CallID": "12345",
    "Address": "123 Elm St",
    "City": "Metropolis",
    "Storelocation": "Main Store",
    "ContactNumber": "555-1234",
    "CustomerEmailID": "johndoe@example.com",
    "ModelNo": "X1000",
    "SerialNo": "SN001234",
    "Status": "Pending",
    "ProblemType": "Battery Issue",
    "CreatedDate": "2025-05-15T08:00:00Z",
    "WarrantyType": "2 Years",
    "Quotation Number": "Q12345",
    "Quotation Status": "Approved",
    "Quotation Date": "2025-05-16",
    "RMA Status": "Processing",
    "RMA Number": "RMA12345",
    "RMA Date": "2025-05-17",
    "Under Repair": "No",
    "Call Number": "CN12345",
    "ETA": "2025-05-18",
    "Repair Date": "2025-05-17",
    "Dispatch": "Yes",
    "Courier Name": "FastShip",
    "Tracking ID": "TRACK12345",
    "Dispacth Date": "2025-05-17"
  },
  {
    "Customer Name": "Jane Smith",
    "CallID": "12346",
    "Address": "456 Oak St",
    "City": "Gotham",
    "Storelocation": "Gotham Store",
    "ContactNumber": "555-5678",
    "CustomerEmailID": "janesmith@example.com",
    "ModelNo": "Y2000",
    "SerialNo": "SN006789",
    "Status": "In Progress",
    "ProblemType": "Screen Crack",
    "CreatedDate": "2025-05-10T08:00:00Z",
    "WarrantyType": "1 Year",
    "Quotation Number": "Q12346",
    "Quotation Status": "Pending",
    "Quotation Date": "2025-05-11",
    "RMA Status": "Not Processed",
    "RMA Number": "",
    "RMA Date": "",
    "Under Repair": "Yes",
    "Call Number": "CN12346",
    "ETA": "2025-05-20",
    "Repair Date": "",
    "Dispatch": "No",
    "Courier Name": "",
    "Tracking ID": "",
    "Dispacth Date": ""
  }
];
