// // src/app/ticket-card/mock-tickets.ts
// // import { Ticket } from '../tickets-list/ticket-card.model';

// export const dummyTickets: Ticket[] = [
//   {
//     'Customer Name': 'John Doe',
//     CallID: 'TCKT-001',
//     Address: '123 MG Road',
//     City: 'Mumbai',
//     Storelocation: 'Andheri',
//     ContactNumber: '+91-9876543210',
//     CustomerEmailID: 'johndoe@example.com',
//     ModelNo: 'Model A1',
//     SerialNo: 'SN001',
//     Status: 'Open',
//     ProblemType: 'Screen Issue',
//     CreatedDate: '2024-05-10',
//     WarrantyType: 'CompWarranty',
//     'Quotation Number': 'Q001',
//     'Quotation Status': 'Pending',
//     'Quotation Date': '2024-05-11',
//     'RMA Status': 'Sent',
//     'RMA Number': 'RMA001',
//     'RMA Date': '2024-05-12',
//     'Under Repair': 'No',
//     'Call Number': 'CALL001',
//     ETA: '2024-05-20',
//     'Repair Date': '',
//     Dispatch: '',
//     'Courier Name': '',
//     'Tracking ID': '',
//     'Dispacth Date': ''
//   },
//   {
//     'Customer Name': 'Jane Smith',
//     CallID: 'TCKT-002',
//     Address: '456 Hill Street',
//     City: 'Delhi',
//     Storelocation: 'Karol Bagh',
//     ContactNumber: '+91-9123456780',
//     CustomerEmailID: 'janesmith@example.com',
//     ModelNo: 'Model B2',
//     SerialNo: 'SN002',
//     Status: 'Closed',
//     ProblemType: 'Battery Issue',
//     CreatedDate: '2024-05-05',
//     WarrantyType: 'OutOfWarranty',
//     'Quotation Number': 'Q002',
//     'Quotation Status': 'Approved',
//     'Quotation Date': '2024-05-06',
//     'RMA Status': 'Delivered',
//     'RMA Number': 'RMA002',
//     'RMA Date': '2024-05-07',
//     'Under Repair': 'Yes',
//     'Call Number': 'CALL002',
//     ETA: '2024-05-15',
//     'Repair Date': '2024-05-10',
//     Dispatch: 'Done',
//     'Courier Name': 'Blue Dart',
//     'Tracking ID': 'BD56789',
//     'Dispacth Date': '2024-05-11'
//   }
// ];
